### PR TITLE
Fix optimisticUpdater

### LINKED ISSUE #69: optimisticUpdater in RemoveCompletedTodosMutation does not work
I checked example. Set slow 3G. Other mutations are immediate, but RemoveCompletedTodosMutation isn't.

screen shot 2018-02-24 at 00 53 53

### PR DESCRIPTION
**Pull request by ntkme**
Closes #69 per conversation on facebook/relay/issues/2345.

- Share the same connection key with `TodoList` to keep the data up to date.
- Dynamically compute `completedTodos` to make sure RemoveCompletedTodosMutation receive correct parameters.

### CODE REVIEW

File: todo/js/components/TodoListFooter.js [hunk 1]
```diff
@@ -20,9 +20,12 @@ import {
 
 class TodoListFooter extends React.Component {
   _handleRemoveCompletedTodosClick = () => {
+    const edges = this.props.viewer.todos.edges.filter(edge => edge.node.complete === true)
```
Comment (alloy) [inline todo/js/components/TodoListFooter.js]: nit: is the `=== true` part really necessary?

**Comment by alloy** [comment]
Nice 👌 

@jstejada LGTM

File: todo/js/components/TodoListFooter.js [hunk 2]
```diff
@@ -52,10 +55,9 @@ export default createFragmentContainer(
     fragment TodoListFooter_viewer on User {
       id,
       completedCount,
-      completedTodos: todos(
-        status: "completed",
+      todos(
         first: 2147483647  # max GraphQLInt
-      ) {
+      ) @connection(key: "TodoList_todos") {
```
Comment (sibelius) [inline todo/js/components/TodoListFooter.js]: maybe we can only remove the todo from TodoList_todos connection where filters is status: 'completed

only getting the right connection https://github.com/facebook/relay/blob/0a4027d4c2328549e2d314dbb5eb8ad1eeaeb051/packages/relay-runtime/handlers/connection/RelayConnectionHandler.js#L243-L250

```
ConnectionHandler.getConnection(proxy, 'TodoList_todos', { status: 'completed')
```

File: todo/js/components/TodoListFooter.js (hunk 1 above)
Comment (ntkme) [reply todo/js/components/TodoListFooter.js]: Not really needed given the server properly return a boolean, but I personally prefer to write it explicitly since many things evaluate to true implicitly in JavaScript.

Comment (alloy) [reply todo/js/components/TodoListFooter.js]: Fair enough.

**Comment by ntkme** [comment]
Amended because I forgot to run linter. It appears the CI does not run linter either...

File: todo/js/components/TodoListFooter.js (hunk 2 above)
Comment (ntkme) [reply todo/js/components/TodoListFooter.js]: Unfortunately, this returns `undefined` rather than a filtered connection.

Comment (ntkme) [reply todo/js/components/TodoListFooter.js]: This returns `undefined` rather than a connection.

https://github.com/facebook/relay/blob/2ba20d1f1e12fa358607d226a8205c9dd04a937d/packages/relay-runtime/mutations/RelayRecordProxy.js#L81-L85

If you look one level down to that call, you will find that the real `storageKey` is a combination of `key` and `filters`, which means we are looking at a connection that never been fetched, thus undefined. Even we fetch that connection, we still face the problem of maintaining the state of that connection on the front-end by either using refetch container or manually update the connection in all other mutations.

**Comment by jstejada** [comment]
Thanks for fixing this @ntkme! I'm going to go ahead and  merge this in the interest of fixing the updater, but I was wondering, should this be a completely separate @connection and move the responsibility to the mutation to update all relevant connections?

What do you think?
